[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "yahooquery"
author = "Doug Guthrie"
author-email = "douglas.p.guthrie@gmail.com"
home-page = "https://github.com/dpguthrie/yahooquery"
classifiers = [
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Intended Audience :: Developers",
    "Intended Audience :: Financial and Insurance Industry",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
requires = [
    "lxml >=4.6.2",
    "pandas >=0.24.0",
    "requests-futures >=1.0.0",
    "tqdm >=4.54.1",
]
description-file = "README.md"

[tool.flit.metadata.urls]
Documentation = "https://yahooquery.dpguthrie.com"
Demo = "https://yahooquery-streamlit.herokuapp.com"

[tool.flit.metadata.requires-extra]
test = [
    "pytest ==6.0.2",
    "pytest-cov==2.10.1",
    "coverage==5.2.1",
]
premium = [
    "selenium >=3.141.0",
]
doc = [
    "mkdocs >=1.1.2,<2.0.0",
    "mkdocs-jupyter >=0.12.0,<0.13.0",
    "mkdocs-material >=6.1.7,<7.0.0",
]
